
export const TRANSITIONS_LOADING  = "TRANSITIONS_LOADING"
export const TRANSITIONS_LOAD     = "TRANSITIONS_LOAD"
export const TRANSITIONS_ERROR_DB = "TRANSITIONS_ERROR_DB"
export const TRANSITIONS_UPDATE   = "TRANSITIONS_UPDATE"
export const TRANSITIONS_NO_OP    = "TRANSITIONS_NO_OP"
