
export const ANSWERS_LOADING  = "ANSWERS_LOADING"
export const ANSWERS_LOAD     = "ANSWERS_LOAD"
export const ANSWERS_ERROR_DB = "ANSWERS_ERROR_DB"
export const ANSWERS_UPDATE   = "ANSWERS_UPDATE"
export const ANSWERS_PERSIST   = "ANSWERS_PERSIST"
