export const MOD_2_DESC = `Welcome to Module 2 of MAPmaker. This week you will examine your social context in order to assess what values and beliefs the people, places and groups in your life possess, and then you will reflect on how these social values and beliefs affect you.`

export const QUES_210_DESC = `In this exercise, you will list the most important <i>contextual influences</i> that impact you in your life.  By contextual influences we mean the most important people, places, cultures, and ideas that are around you. Contextual influences are an important place to start a self-reflection process because we are all social beings who live among a continual throng of ideas, opinions, values, beliefs, and expectations. These influential voices shape us and inform how we live, think, and behave in our everyday life. This first exercise is designed to give you the opportunity to which of these surrounding influences are most important to you.
<br><br>
In order to help you be thorough, we have divided your possible influences into three categories:  <i>Personal Relationships</i>, <i>Social Groups and Ideologies</i>, and <i>Wider Communities & Cultural Groups</i>.
<br><br>
<b>List your most important contextual influences.</b>  In this first session, simply fill in the names of any influences that are meaningful to you in your current or past life, whether they are positively supportive of who you are and who you want to become, negatively inhibiting of who you are and who you want to become, or both supportive and inhibiting to you are and who you want to become (some of our influences support us in some ways, but inhibit us in others). You are free to fill in as many influences as you would like as long as the influences are meaningful and impactful to your current life or past development. This exercise provides you the opportunity to think about how the people and forces in your life have influenced who you are.
<br><br>
Below are the 3 categories of influences listed on in your workbook along with some specific examples of types of influences within each category.
<br><br>
<i>1. Personal Relationships:</i>  These are all the individuals who now or in the past have directly influenced you positively, negatively, or both. (Examples:  mother, father, step parents, brothers, sisters, grandparents, aunts, uncles, cousins, teachers, coaches, mentors, religious leaders, neighbors, friends from different eras, parents’ friends, camp counselors, bosses, etc…).  Feel free to list these or any other personal relationships that have influenced you.
<br><br>
<i>2. Social Groups and Ideologies:</i>  These are specific groups to which you belong or have belonged, or schools of thought and ideologies to which you have subscribed.  These affiliations can be personally chosen or not. (Examples: schools, colleges, teams, religious communities, thought leaders [such as philosophers, theologians, self-help writers, artists, media personalities], youth groups, clubs, fraternities/sororities, civic organizations, volunteer activities, jobs, companies, affinity groups, etc…). Feel free to list these or any other social groups or ideologies that have influenced you.
<br><br>
<i>3. Wider Communities and Cultural Groups:</i>  These are also groups to which you belong or have belonged, but the scope is much wider. As a result, the influence may be a bit more indirect. (Examples:  cities, towns, states, countries, neighborhoods, ethnicities, genders, socio-economic sectors, educational groups, industries, etc…). Feel free to list these or any other communities or cultural groups that have influenced you.
<br><br>
<b>Choose the values and beliefs of your influences.</b> Your surrounding influences offer you a mix of values and beliefs.  By 'values and beliefs' we mean the things that they care about, how they see the world, and the ideas that they impressed on you directly or indirectly. Some of your influences may seem entirely positive and supportive to your well-being (e.g., a teacher who saw your potential and championed your growth), others may seem entirely negative and inhibiting to your growth, development, or authenticity (e.g., a teacher who was overly critical and squelched your growth), and sometimes influences may be both supportive and inhibiting in different ways (e.g., parents who provide some supporting love and stability, but who also inhibit your growth because they do not understand some of your needs, strengths, or personal vision).  Therefore we have included space for both 'supportive' and 'inhibiting' values and beliefs for each influence that you listed.  Beside each influence, list as many 'supportive' and/or 'inhibiting' values and beliefs as you think are relevant.  Once you have completed your list of <i>Personal Relationships</i>, please do the same for <i>Social Groups and Ideologies</i>, and then for <i>Wider Communities and Cultural Groups</i>.
<br><br>
Next is a list of possible positive values and beliefs.  You may use this list to choose 'supportive' values. You may also use the list to help you think about the values that your influences may have inhibited you from (e.g., seeing 'Bravery' in the list may help you realize that your influence 'inhibited' you from this value by impressing 'fearfulness' or 'anxiety' on you). You may choose from this list or write in any other value and belief that is relevant or characteristic of your influence.
<br><br>
Beside each value you listed, choose whether the value is 'supportive' or 'inhibiting.'`

export const QUES_220_DESC = `In the previous exercise you listed the values and beliefs of the influences around you. Today you will choose which of these values and beliefs were most important to you. The values and beliefs have been separated into the two categories so that you can focus initially on the supportive values and beliefs that you want to 'build upon,' and then on the inhibiting values and beliefs that you would like to 'break from.'
<br><br>
Choose your most important influences.  Choose your top 5 'supportive' values and beliefs according to how influential or important someone’s, or some group’s, values and beliefs have been upon you. For values and beliefs that you identified as similar to another influence (e.g., for parent 2 you wrote 'same as parent 1 supportive belief'), just choose one since you already chose those values and beliefs elsewhere.
Once you have completed the ranking of your 'supportive' values, do the same for your top 5 'inhibiting' values.`

export const QUES_230_DESC = QUES_220_DESC

export const QUES_240_DESC = `Based on what you have written for your top 5 supportive and top 5 inhibiting influences, fill in the blanks of the statement provided in order to more fully understand the relationships between your own personal values and beliefs, and the values and beliefs of your top influences.`

export const QUES_250_DESC = `Based on what you have written for your top 5 supportive and top 5 inhibiting influences, fill in the blanks of the statement provided in order to more fully understand the relationships between your own personal values and beliefs, and the values and beliefs of your top influences.`

export const QUES_260_DESC = `Review and compare the 'supportive' and 'inhibiting' Self-Acceptance statements from Exercise 3.  Look for ways in which the two statements reflect each other, and for ways in which they reflect differing things from each other.`

export const QUES_270_DESC = `In order to create a more meaningful life, consider which values and beliefs need to be 'broken from,' and which values and beliefs need to be 'built toward.' Fill in the following blanks:
<br><br>
In order to create a more meaningful life, I want to embrace more authentic Self-acceptance by altering my:`
