export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'
export const FIRSTNAME_CHANGED = 'firstname_changed'
export const LASTNAME_CHANGED = 'lastname_changed'
export const SIGNUP = 'signup'

export const USER_UPDATE_CURR_SECTION = 'USER_UPDATE_CURR_SECTION'
export const USER_UPDATE_CURR_SECTION_NO_CHANGE = 'USER_UPDATE_CURR_SECTION_NO_CHANGE'
export const USER_UPDATE_ERROR = 'USER_UPDATE_FAILED'
